name: Nightly Build
on:
  - push
  - workflow_dispatch
jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from source code.
        run: |
          >> $GITHUB_ENV echo PKG_VER=$(egrep 'VERSION\s+=' src/AozoraEpub3.java | awk -F '"' '{print $2}')
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'
      - run: gradle build
      - run: mkdir -p bin
      - run: gradle create_run_jar
      - run: cp -v build/libs/AozoraEpub3.jar out/
      - run: cp -vr lib/LICENSE out/
      - uses: actions/upload-artifact@v4
        with:
          name: AozoraEpub3-${{ env.PKG_VER }}
          path: out/